### ISSUE TITLE
RecSim Visualization breaks sometimes

### ISSUE THREAD

**Issue by pecey** [ataitler/pyRDDLGym#193]
The RecSim visualization breaks sometimes.  The stacktrace is as follows:
```
Traceback (most recent call last):
  File "main.py", line 228, in <module>
    main(args)
  File "main.py", line 206, in main
    run(cfg, args.n_episodes, key, env, cfg_env, g_obs_keys, ga_keys, args.render)
  File "main.py", line 83, in run
    env.render()
  File "/nfs/nfs2/home/palchatt/Research/IPC23/pyRDDLGymHelper/Core/Env/RDDLEnv.py", line 253, in render
    image = self._visualizer.render(self.state)
  File "/nfs/nfs2/home/palchatt/Research/IPC23/pyRDDLGymHelper/Visualizer/RecSimViz.py", line 138, in render
    self._user_plot = self._ax_scatter.scatter(
  File "/nfs/nfs9/home/nobackup/palchatt/ipc23/lib/python3.8/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/nfs/nfs9/home/nobackup/palchatt/ipc23/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4673, in scatter
    collection = mcoll.PathCollection(
  File "/nfs/nfs9/home/nobackup/palchatt/ipc23/lib/python3.8/site-packages/matplotlib/collections.py", line 996, in __init__
    self.set_sizes(sizes)
  File "/nfs/nfs9/home/nobackup/palchatt/ipc23/lib/python3.8/site-packages/matplotlib/collections.py", line 963, in set_sizes
    scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor
FloatingPointError: invalid value encountered in sqrt
```

My guess is that maybe some of the state values are becoming too small. Maybe rounding off the state values to a certain precision?

**Comment by mike-gimelfarb** [comment]
Thanks for the report. This is a difficult one to test because it happens around 1% of the time with the random policy.
I just submitted a fix. If it happens again please let me know.
Thanks.

**Comment by mike-gimelfarb** [comment]
I am closing this issue. If you encounter the problem again, please feel free to post another issue.
